# PiDrive WirePlumber BT-Konfiguration
# A2DP für BMW iDrive (Pi als Audio-Source/Sender)
monitor.bluez.properties = {
    bluez5.roles = [ a2dp_source hfp_ag ]
    bluez5.codecs = [ sbc ]
    bluez5.auto-connect = [ a2dp_source ]
    bluez5.hw-volume = [ a2dp_source ]
}
